services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  temporal:
    image: temporalio/auto-setup:1.24.2
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=app
      - POSTGRES_PWD=app
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"
    depends_on:
      - postgres

  temporal-ui:
    image: temporalio/ui:2.31.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    ports:
      - "8233:8080"
    depends_on:
      - temporal

  api:
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    environment:
      - DATABASE_URL=postgresql://app:app@postgres:5432/app
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  agent:
    build:
      context: ../
      dockerfile: apps/agent/Dockerfile
    ports:
      - "8083:8083"

  worker:
    build:
      context: ../
      dockerfile: apps/worker/Dockerfile
    depends_on:
      - temporal

  web:
    build:
      context: ../
      dockerfile: apps/web/Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8081
    ports:
      - "3000:80"
    depends_on:
      - api

  # Kafka and Zookeeper temporarily disabled - can be added later
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.4.0
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:7.4.0
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "29092:29092"

volumes:
  pgdata:


